### ISSUE TITLE
Ignore option does not add util to breakpoints

### ISSUE THREAD

**Issue by jondashkyle** [jongacnik/gr8#3]
When adding a util to the `ignore` option, it does not get added to breakpoints if the `responsive` option is enabled. Planning to fix this one, but trying to wrap up a project, so will circle around and submit a pull request soon.

**Comment by jongacnik** [comment]
Guessing this issue is in relation to [lilcss](https://github.com/jongacnik/lilcss)?

**Comment by jondashkyle** [comment]
Oh, right !
