### ISSUE TITLE
Readme Examples Clarification

### ISSUE THREAD

**Issue by gdenisov** [jongacnik/gr8#6]
Documentation cites a custom `text-color` property as an example multiple times. Wouldn't it make more sense to do a custom `color` property as there is no text-color in CSS spec?

**Comment by jongacnik** [comment]
wowwza! 😳 great catch, gonna tweak...

**Comment by jongacnik** [comment]
Replaced `text-color` with `background-color` because I think it's nice in the example to hint at the  hyphen → abbreviation.
