### ISSUE TITLE
Consider per utility breakpoints

### ISSUE THREAD

**Issue by jongacnik** [jongacnik/gr8#8]
It might be handy to be able to define breakpoints on a per utility basis. Examples to follow...

**Comment by freder** [comment]
or setting `responsive` to `true|false` per util, in general.

**Comment by jongacnik** [comment]
Agreed! Actually working on a bit of a rewrite under the hood; each util is just becoming a small function call so passing in specific options like this will be much more straightforward. Trying to make some progress this weekend

**Comment by jongacnik** [comment]
Closing this as 3.0.0 is now released  #17 

This didn't make it's way in, but now with access to some [lower level helpers](https://github.com/jongacnik/gr8#proxies) there are ways to roll a more custom build for advanced usage
